# 网站信息
url:                "http://www.xatusec.org"                            # 地址
title:              "XATUSEC"                                           # 标题
email:              "root@xatusec.org"                                  # 邮箱
description:        "西安工业大学绿色兵团"                              # 简介

# 编译设置
markdown: kramdown                                                      # MarkDown

# 第三方设置
duoshuo_user:       "xatusec"                                           # 多说账号
cnzz_id:            "1254831492"                                        # cnzz统计id    

# CDN设置
bootstrapCdnUrl:    "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4"                # bootstrap cnd url
jqueryCdnUrl:       "http://lib.sinaapp.com/js/jquery/2.0.3/jquery-2.0.3.min.js"    # jquery cdn url
